import type { WorkflowRecord } from "./types";

export const workflowRecords: WorkflowRecord[] = [
  {
    id: "route-compare",
    name: "路径方案比选流",
    code: "route-compare",
    emoji: "🛣️",
    description: "串联路径生成、合规校核、敏感点分析和方案排序，形成比选结论。",
    status: "运行中",
    metrics: [
      { label: "节点", value: "12" },
      { label: "技能", value: "4" },
      { label: "工具", value: "6" },
      { label: "发布", value: "v3" },
    ],
    tags: ["方案比选", "自动汇总", "常用"],
    summary: {
      scenario: "针对线路候选路径做自动比选，汇总约束、成本和风险。",
      input: "路径草案、区域红线、地形数据、历史经验规则。",
      output: "方案排序、关键风险点、推荐结论与汇总说明。",
    },
    nodes: [
      {
        id: "START",
        kind: "start",
        title: "开始节点",
        subtitle: "接收任务输入",
        detail: "录入路径草案、区域约束和项目参数，生成统一的工作流上下文。",
        output: "候选路径包与项目基础参数",
      },
      {
        id: "LLM-01",
        kind: "llm",
        title: "路径预分析",
        subtitle: "LLM 提炼比选目标",
        detail: "根据项目意图识别重点约束，生成后续节点要使用的分析维度。",
        output: "比选维度、优先级和说明口径",
      },
      {
        id: "TOOL-01",
        kind: "tool",
        title: "合规校核",
        subtitle: "调用规则与 GIS 工具",
        detail: "批量检查保护区、居民点、交通跨越和既有线路冲突情况。",
        output: "路径合规问题清单",
      },
      {
        id: "TOOL-02",
        kind: "tool",
        title: "敏感点分析",
        subtitle: "空间分析工具",
        detail: "计算每条候选路径的敏感点数量、绕行距离和施工难度指数。",
        output: "敏感点画像与量化得分",
      },
      {
        id: "CONDITION",
        kind: "condition",
        title: "方案分流",
        subtitle: "按风险阈值筛选",
        detail: "剔除高风险路径，保留可研阶段可继续推进的方案。",
        output: "可行路径集合",
      },
      {
        id: "TEMPLATE",
        kind: "template",
        title: "结论汇总",
        subtitle: "模板化生成说明",
        detail: "拼装排序结果、约束摘要和推荐理由，形成标准输出口径。",
        output: "比选结论说明",
      },
      {
        id: "END",
        kind: "end",
        title: "结束节点",
        subtitle: "输出推荐方案",
        detail: "返回排序结果、风险摘要和建议结论，供页面展示与导出。",
        output: "推荐路径与比选摘要",
      },
    ],
    edges: [
      { from: "START", to: "LLM-01", label: "意图解析" },
      { from: "LLM-01", to: "TOOL-01", label: "规则校核" },
      { from: "TOOL-01", to: "TOOL-02", label: "敏感点计算" },
      { from: "TOOL-02", to: "CONDITION", label: "风险筛选" },
      { from: "CONDITION", to: "TEMPLATE", label: "汇总结论" },
      { from: "TEMPLATE", to: "END", label: "输出结果" },
    ],
    runLogs: [
      { label: "本次输入", value: "3 条候选路径，覆盖 2 个行政区，目标为推荐最优可研方案。" },
      { label: "关键判断", value: "路径 B 存在生态红线冲突，路径 C 敏感点较少但造价更高，路径 A 综合得分最高。" },
      { label: "最终产出", value: "推荐路径 A，附带 2 个备选方案和风险说明。" },
    ],
  },
  {
    id: "report-review",
    name: "报告校审流",
    code: "report-review",
    emoji: "📘",
    description: "组合通用校审、标准引用校验和图表一致性检查，输出校审问题清单。",
    status: "运行中",
    metrics: [
      { label: "节点", value: "9" },
      { label: "技能", value: "5" },
      { label: "工具", value: "7" },
      { label: "发布", value: "v5" },
    ],
    tags: ["报告校审", "批量处理", "质量控制"],
    summary: {
      scenario: "对报告正文、图表和标准引用做统一校审。",
      input: "报告文件、校审清单、标准规范库。",
      output: "问题清单、风险等级和修订建议。",
    },
    nodes: [
      {
        id: "START",
        kind: "start",
        title: "开始节点",
        subtitle: "接收校审任务",
        detail: "读取报告文件、章节结构和适用标准，准备校审上下文。",
        output: "报告文本与附件索引",
      },
      {
        id: "LLM-01",
        kind: "llm",
        title: "章节拆解",
        subtitle: "识别校审重点",
        detail: "按章节、图表和附录拆出待检查单元，标定关键风险区域。",
        output: "校审片段队列",
      },
      {
        id: "TOOL-01",
        kind: "tool",
        title: "标准引用校验",
        subtitle: "规则工具",
        detail: "检查规范名称、版本号和引用位置是否一致。",
        output: "引用问题列表",
      },
      {
        id: "TOOL-02",
        kind: "tool",
        title: "图表一致性检查",
        subtitle: "图文比对工具",
        detail: "核对正文、图表和表格中的关键数值与描述是否对齐。",
        output: "图文差异项",
      },
      {
        id: "END",
        kind: "end",
        title: "结束节点",
        subtitle: "汇总问题清单",
        detail: "按严重程度整理问题项，返回修改建议和定位信息。",
        output: "校审结果包",
      },
    ],
    edges: [
      { from: "START", to: "LLM-01", label: "切分任务" },
      { from: "LLM-01", to: "TOOL-01", label: "规范校验" },
      { from: "TOOL-01", to: "TOOL-02", label: "交叉核对" },
      { from: "TOOL-02", to: "END", label: "形成结果" },
    ],
    runLogs: [
      { label: "本次输入", value: "共 1 份报告，17 个章节，38 张图表。" },
      { label: "关键判断", value: "发现 4 处规范版本引用不一致，2 处图表数据与正文表述冲突。" },
      { label: "最终产出", value: "输出 6 条校审问题，并标注章节位置与建议修订方式。" },
    ],
  },
  {
    id: "agreement-generate",
    name: "协议资料生成流",
    code: "agreement-generate",
    emoji: "📝",
    description: "根据线路路径、行政区划和部门映射，自动生成路径协议与资料包。",
    status: "待排期",
    metrics: [
      { label: "节点", value: "7" },
      { label: "技能", value: "3" },
      { label: "工具", value: "4" },
      { label: "触发", value: "人工" },
    ],
    tags: ["资料生成", "审批前置"],
    summary: {
      scenario: "按路径与行政区划自动拼装协议资料。",
      input: "线路路径、乡镇村落信息、单位映射规则。",
      output: "协议正文、盖章清单与资料包。",
    },
    nodes: [
      {
        id: "START",
        kind: "start",
        title: "开始节点",
        subtitle: "接收线路资料",
        detail: "读取路径坐标、行政区划和项目基础信息。",
        output: "路径坐标与项目信息",
      },
      {
        id: "TOOL-01",
        kind: "tool",
        title: "部门映射",
        subtitle: "匹配属地单位",
        detail: "根据路径覆盖范围匹配审批单位、联系人和资料模板。",
        output: "部门映射结果",
      },
      {
        id: "TEMPLATE",
        kind: "template",
        title: "协议拼装",
        subtitle: "模板输出资料",
        detail: "将项目信息回填到协议和附件模板中，生成标准文档。",
        output: "协议正文与附件",
      },
      {
        id: "END",
        kind: "end",
        title: "结束节点",
        subtitle: "生成资料包",
        detail: "输出协议资料、清单和交付说明，供人工复核。",
        output: "审批资料包",
      },
    ],
    edges: [
      { from: "START", to: "TOOL-01", label: "映射单位" },
      { from: "TOOL-01", to: "TEMPLATE", label: "填充模板" },
      { from: "TEMPLATE", to: "END", label: "打包导出" },
    ],
    runLogs: [
      { label: "本次输入", value: "涉及 2 个乡镇、5 个村组、1 条线路走廊。" },
      { label: "关键判断", value: "匹配到 3 套协议模板，需补充 1 份乡镇联系人信息。" },
      { label: "最终产出", value: "生成协议正文 3 份、附件清单 1 份、盖章说明 1 份。" },
    ],
  },
  {
    id: "tower-batch",
    name: "塔重估测批处理流",
    code: "tower-batch",
    emoji: "🏗️",
    description: "接收一批工况条件后批量调用塔重估测服务，统一产出预测结果和汇总表。",
    status: "草稿",
    metrics: [
      { label: "节点", value: "5" },
      { label: "技能", value: "2" },
      { label: "工具", value: "3" },
      { label: "触发", value: "定时" },
    ],
    tags: ["批处理", "塔重估测"],
    summary: {
      scenario: "批量提交工况，统一返回塔重估测结果。",
      input: "工况表、模型参数、批处理批次号。",
      output: "预测结果表、异常项和汇总统计。",
    },
    nodes: [
      {
        id: "START",
        kind: "start",
        title: "开始节点",
        subtitle: "读取批次参数",
        detail: "获取待处理工况、批次号和调度配置。",
        output: "批处理任务清单",
      },
      {
        id: "TOOL-01",
        kind: "tool",
        title: "模型调用",
        subtitle: "批量预测服务",
        detail: "循环提交工况数据，返回每条记录的塔重预测结果。",
        output: "预测结果明细",
      },
      {
        id: "CONDITION",
        kind: "condition",
        title: "异常筛选",
        subtitle: "识别异常波动",
        detail: "按阈值筛选预测异常项，并记录失败原因。",
        output: "异常记录列表",
      },
      {
        id: "END",
        kind: "end",
        title: "结束节点",
        subtitle: "输出汇总结果",
        detail: "形成总表、异常清单和批处理摘要，供后续下载。",
        output: "批处理结果包",
      },
    ],
    edges: [
      { from: "START", to: "TOOL-01", label: "提交预测" },
      { from: "TOOL-01", to: "CONDITION", label: "识别异常" },
      { from: "CONDITION", to: "END", label: "汇总结果" },
    ],
    runLogs: [
      { label: "本次输入", value: "共 128 条工况，定时任务于 02:00 自动触发。" },
      { label: "关键判断", value: "发现 3 条异常记录，原因分别为参数缺失、风速越界和服务超时。" },
      { label: "最终产出", value: "输出预测总表 1 份，异常清单 1 份，统计摘要 1 份。" },
    ],
  },
];

export function getWorkflowById(id: string) {
  return workflowRecords.find((workflow) => workflow.id === id) ?? null;
}
