import type { BotRecord } from "./types";

export const bots: BotRecord[] = [
  {
    id: "main",
    name: "小虾",
    code: "main",
    emoji: "🦐",
    description: "负责架构设计、程序设计、代码编写与问题排查。",
    status: "活跃",
    sandboxEnabled: false,
    metrics: [
      { label: "会话", value: "23" },
      { label: "技能", value: "12" },
      { label: "工具", value: "8" },
      { label: "沙箱", value: "关" },
    ],
    tags: ["主 Bot", "研发", "高权限"],
  },
  {
    id: "coding",
    name: "代码工匠",
    code: "coding",
    emoji: "💻",
    description: "偏向代码质量治理、重构建议和技术文档输出。",
    status: "活跃",
    sandboxEnabled: true,
    metrics: [
      { label: "会话", value: "8" },
      { label: "技能", value: "5" },
      { label: "工具", value: "4" },
      { label: "沙箱", value: "开" },
    ],
    tags: ["代码审查", "文档"],
  },
  {
    id: "family",
    name: "家庭助手",
    code: "family",
    emoji: "👨‍👩‍👧‍👦",
    description: "服务家庭场景，工具受限，优先保证安全边界。",
    status: "空闲",
    sandboxEnabled: true,
    metrics: [
      { label: "会话", value: "45" },
      { label: "技能", value: "3" },
      { label: "工具", value: "2" },
      { label: "沙箱", value: "开" },
    ],
    tags: ["安全隔离", "家庭"],
  },
  {
    id: "analyst",
    name: "数据分析师",
    code: "analyst",
    emoji: "📊",
    description: "负责数据清洗、洞察提炼、图表生成和报告撰写。",
    status: "草稿",
    sandboxEnabled: true,
    metrics: [
      { label: "会话", value: "2" },
      { label: "技能", value: "1" },
      { label: "工具", value: "1" },
      { label: "沙箱", value: "开" },
    ],
    tags: ["草稿", "分析"],
  },
];
