import type { BotRecord } from "./types";

export const bots: BotRecord[] = [
  {
    id: "main",
    name: "小虾",
    code: "main",
    emoji: "🦐",
    role: "全栈技术专家",
    description: "负责架构设计、程序设计、代码编写与问题排查。",
    status: "活跃",
    model: "anthropic/claude-opus-4.1",
    workspace: "~/workspace/openclaw",
    agentPath: "~/.openclaw/agents/main",
    sandboxEnabled: false,
    updatedAt: "2 小时前编辑",
    metrics: [
      { label: "会话", value: "23" },
      { label: "记忆", value: "12" },
      { label: "工具", value: "8" },
    ],
    channels: [
      { id: "whatsapp", label: "WhatsApp" },
      { id: "telegram", label: "Telegram" },
      { id: "webchat", label: "WebChat" },
    ],
    tags: ["主 Bot", "研发", "高权限"],
  },
  {
    id: "coding",
    name: "代码工匠",
    code: "coding",
    emoji: "💻",
    role: "代码审查与重构专家",
    description: "偏向代码质量治理、重构建议和技术文档输出。",
    status: "活跃",
    model: "openai/gpt-5.4",
    workspace: "~/workspace/coding-bot",
    agentPath: "~/.openclaw/agents/coding",
    sandboxEnabled: true,
    updatedAt: "今天 09:20",
    metrics: [
      { label: "会话", value: "8" },
      { label: "记忆", value: "5" },
      { label: "工具", value: "4" },
    ],
    channels: [{ id: "discord", label: "Discord" }],
    tags: ["代码审查", "文档"],
  },
  {
    id: "family",
    name: "家庭助手",
    code: "family",
    emoji: "👨‍👩‍👧‍👦",
    role: "家庭群聊机器人",
    description: "服务家庭场景，工具受限，优先保证安全边界。",
    status: "空闲",
    model: "openai/gpt-4.1",
    workspace: "~/workspace/family-bot",
    agentPath: "~/.openclaw/agents/family",
    sandboxEnabled: true,
    updatedAt: "昨天 18:10",
    metrics: [
      { label: "会话", value: "45" },
      { label: "记忆", value: "3" },
      { label: "工具", value: "2" },
    ],
    channels: [{ id: "whatsapp-family", label: "WhatsApp 家庭群" }],
    tags: ["安全隔离", "家庭"],
  },
  {
    id: "analyst",
    name: "数据分析师",
    code: "analyst",
    emoji: "📊",
    role: "数据清洗与可视化分析",
    description: "负责数据清洗、洞察提炼、图表生成和报告撰写。",
    status: "草稿",
    model: "openai/gpt-4.1-mini",
    workspace: "~/workspace/analyst-bot",
    agentPath: "~/.openclaw/agents/analyst",
    sandboxEnabled: true,
    updatedAt: "3 天前编辑",
    metrics: [
      { label: "会话", value: "2" },
      { label: "记忆", value: "1" },
      { label: "工具", value: "1" },
    ],
    channels: [],
    tags: ["草稿", "分析"],
  },
];
