import { createTemplateRecord, listStrategyTemplates } from "@/knowhub/features/strategies/registry";
import type { StrategyRecord } from "@/knowhub/features/strategies/types";

export const strategyRecords: StrategyRecord[] = [
  ...listStrategyTemplates().map((item) => createTemplateRecord(item)),
  {
    id: "excel-xls-to-xlsx",
    name: "XLS 转 XLSX",
    category: "preprocess",
    group: "Excel",
    summary: "将旧版 .xls 文件转换为 .xlsx，保留原始格式、样式、公式和图表结构。",
    metaLabel: "格式",
    metaValue: "XLS / XLSX",
    owner: "知识工程组",
    usageCount: 186,
  },
  {
    id: "excel-sheet-split",
    name: "Excel Sheet 拆分",
    category: "preprocess",
    group: "Excel",
    summary: "将多 Sheet 工作簿拆分为多个单 Sheet 文件，保留原始样式和数据结构。",
    metaLabel: "格式",
    metaValue: "XLSX",
    owner: "知识工程组",
    usageCount: 72,
  },
  {
    id: "excel-table-clean",
    name: "Excel 表体检测清洗",
    category: "preprocess",
    group: "Excel",
    summary: "自动识别表体边界，清除表体外无关列与备注信息，保留核心表格内容。",
    metaLabel: "格式",
    metaValue: "XLSX",
    owner: "线路设计组",
    usageCount: 94,
  },
  {
    id: "excel-header-clean",
    name: "Excel 标题与表头清洗",
    category: "preprocess",
    group: "Excel",
    summary: "自动识别标题行和复杂表头，处理多行表头合并，规范化表格结构。",
    metaLabel: "格式",
    metaValue: "XLSX",
    owner: "知识工程组",
    usageCount: 83,
  },
  {
    id: "excel-data-mask",
    name: "Excel 数据脱敏",
    category: "preprocess",
    group: "Excel",
    summary: "将数字、百分比等敏感内容随机化处理，同时保持原始样式和格式不变。",
    metaLabel: "格式",
    metaValue: "XLSX",
    owner: "知识工程组",
    usageCount: 57,
  },
  {
    id: "word-doc-to-docx",
    name: "DOC 转 DOCX",
    category: "preprocess",
    group: "Word",
    summary: "统一将旧版 .doc 文档转换为 .docx，保留文档格式、样式和正文内容。",
    metaLabel: "格式",
    metaValue: "DOC / DOCX",
    owner: "知识工程组",
    usageCount: 121,
  },
  {
    id: "word-to-pdf",
    name: "Word 转 PDF",
    category: "preprocess",
    group: "Word",
    summary: "将 Word 文档批量转换为 PDF，保留原始格式和版式，便于统一归档与共享。",
    metaLabel: "格式",
    metaValue: "DOC / DOCX / PDF",
    owner: "知识工程组",
    usageCount: 109,
  },
  {
    id: "word-header-footer-clean",
    name: "页眉页脚清理",
    category: "preprocess",
    group: "Word",
    summary: "清理 DOCX 文档中的页眉页脚元素，用于规范化文本和后续知识入库。",
    metaLabel: "格式",
    metaValue: "DOCX",
    owner: "知识工程组",
    usageCount: 88,
  },
  {
    id: "word-table-extract",
    name: "Word 表格提取",
    category: "preprocess",
    group: "Word",
    summary: "提取 Word 文档中的表格并输出独立 Excel，保留表格样式和合并单元格关系。",
    metaLabel: "格式",
    metaValue: "DOCX / XLSX",
    owner: "知识工程组",
    usageCount: 76,
  },
  {
    id: "pdf-to-markdown",
    name: "PDF 转 Markdown",
    category: "preprocess",
    group: "PDF",
    summary: "将 PDF 文档转换为结构化 Markdown 文本，便于后续切片、检索和知识沉淀。",
    metaLabel: "格式",
    metaValue: "PDF / Markdown",
    owner: "算法组",
    usageCount: 203,
  },
  {
    id: "chunk-fixed-overlap",
    name: "固定长度重叠切片",
    category: "chunking",
    group: "正文类",
    summary: "按固定字数或 token 切分并保留重叠窗口，适合 OCR 文本和结构较弱的材料。",
    metaLabel: "方式",
    metaValue: "固定长度+重叠",
    owner: "算法组",
    usageCount: 97,
  },
  {
    id: "chunk-page-window",
    name: "页码窗口切片",
    category: "chunking",
    group: "正文类",
    summary: "按页切分并保留前后页标题和过渡段，适合页级报告和扫描文档场景。",
    metaLabel: "方式",
    metaValue: "页码窗口",
    owner: "算法组",
    usageCount: 53,
  },
  {
    id: "chunk-heading-window",
    name: "标题窗口切片",
    category: "chunking",
    group: "正文类",
    summary: "按标题范围组织正文块，超长时再细切，同时保留标题窗口和章节路径。",
    metaLabel: "方式",
    metaValue: "标题窗口",
    owner: "知识工程组",
    usageCount: 84,
  },
  {
    id: "chunk-heading",
    name: "标题层级切片",
    category: "chunking",
    group: "正文类",
    summary: "按照标题与子标题切片，保留章节层级，适合规范、制度和报告正文。",
    metaLabel: "粒度",
    metaValue: "标题层级",
    owner: "知识工程组",
    usageCount: 243,
  },
  {
    id: "chunk-numbered-list",
    name: "编号枚举切片",
    category: "chunking",
    group: "正文类",
    summary: "将“1、2、3”或“（一）（二）（三）”这类编号条目拆成独立切片，便于逐项检索。",
    metaLabel: "对象",
    metaValue: "编号条目",
    owner: "校审组",
    usageCount: 61,
  },
  {
    id: "chunk-parent-child",
    name: "父子上下文切片",
    category: "chunking",
    group: "正文类",
    summary: "保留父级摘要和子级正文，适合长章节、多层目录场景的检索召回。",
    metaLabel: "粒度",
    metaValue: "父子上下文",
    owner: "算法组",
    usageCount: 131,
  },
  {
    id: "chunk-semantic-paragraph",
    name: "语义段落切片",
    category: "chunking",
    group: "正文类",
    summary: "按语义相近的连续段落聚合切片，避免机械截断，适合技术说明和论证正文。",
    metaLabel: "方式",
    metaValue: "语义聚合",
    owner: "算法组",
    usageCount: 116,
  },
  {
    id: "chunk-table-row",
    name: "表格行记录切片",
    category: "chunking",
    group: "表格类",
    summary: "按表格单行或一组关联行切分，并保留表头，适合清册、台账和统计表。",
    metaLabel: "粒度",
    metaValue: "单行记录",
    owner: "知识工程组",
    usageCount: 142,
  },
  {
    id: "chunk-table-topic",
    name: "表格主题切片",
    category: "chunking",
    group: "表格类",
    summary: "按表格主题字段聚合成块，不按行拆散，适合汇总表、对比表和指标表。",
    metaLabel: "粒度",
    metaValue: "主题表块",
    owner: "算法组",
    usageCount: 88,
  },
  {
    id: "chunk-faq",
    name: "问答对切片",
    category: "chunking",
    group: "其它",
    summary: "将 FAQ、答疑记录和意见回复拆成问答单元，适合直接问答召回。",
    metaLabel: "对象",
    metaValue: "问答单元",
    owner: "校审组",
    usageCount: 58,
  },
  {
    id: "chunk-standard-clause",
    name: "标准条文切片",
    category: "chunking",
    group: "其它",
    summary: "按条号、条文正文和适用说明切分，强保留编号，适合标准规范和制度条文。",
    metaLabel: "对象",
    metaValue: "条号条文",
    owner: "知识工程组",
    usageCount: 104,
  },
  {
    id: "chunk-figure-note",
    name: "图表说明切片",
    category: "chunking",
    group: "其它",
    summary: "将图表标题、图注表注和附近说明文字合并切分，适合图文混排说明材料。",
    metaLabel: "对象",
    metaValue: "图表说明",
    owner: "算法组",
    usageCount: 47,
  },
  {
    id: "extract-table-fields",
    name: "表格字段提取",
    category: "extract",
    group: "表格提取",
    summary: "从表格中提取字段名、值和行列关系，输出适合入库的结构化结果。",
    metaLabel: "格式",
    metaValue: "Excel / Word 表格",
    owner: "算法组",
    usageCount: 41,
  },
  {
    id: "extract-summary-points",
    name: "要点摘要提取",
    category: "extract",
    group: "要点提取",
    summary: "提取段落、章节和附件中的关键信息，输出摘要要点和引用位置。",
    metaLabel: "格式",
    metaValue: "Word / PDF",
    owner: "知识工程组",
    usageCount: 29,
  },
  {
    id: "extract-entity-pairs",
    name: "实体关系提取",
    category: "extract",
    group: "实体提取",
    summary: "从文本中抽取工程实体、指标和值之间的关系，用于结构化知识沉淀。",
    metaLabel: "格式",
    metaValue: "Markdown / 文本",
    owner: "算法组",
    usageCount: 17,
  },
];
