import type { PipelineRecord } from "@/knowhub/features/knowledge/types";

export const pipelineRecords: PipelineRecord[] = [
  {
    id: "standard-library",
    name: "标准规范知识库",
    summary: "按默认全局策略处理规范正文与条文内容，沉淀统一的标准规范知识库。",
    status: "published",
    docspaceIds: ["design-hosted"],
    targetLabel: "标准规范目录 / PDF + DOCX",
    preprocessStrategyIds: ["pdf-to-markdown", "word-doc-to-docx"],
    chunkingStrategyIds: ["chunk-heading", "chunk-standard-clause"],
    extractStrategyIds: ["extract-entity-pairs"],
    embeddingModel: "bge-m3",
    knowledgeTarget: "标准规范知识库",
    lastRunAt: "2026-03-31 10:18",
    runCount: 12,
  },
  {
    id: "review-library",
    name: "校审经验知识库",
    summary: "面向校审成果、标准比对和闭环资料，按表格与正文混合策略生成校审经验知识库。",
    status: "running",
    docspaceIds: ["review-smb", "agreement-oss"],
    targetLabel: "校审成果目录 / Excel + PDF",
    preprocessStrategyIds: ["excel-table-clean", "excel-header-clean", "pdf-to-markdown"],
    chunkingStrategyIds: ["chunk-table-row", "chunk-numbered-list", "chunk-page-window"],
    extractStrategyIds: ["extract-table-fields", "extract-summary-points"],
    embeddingModel: "text-embedding-3-large",
    knowledgeTarget: "校审经验知识库",
    lastRunAt: "2026-03-31 09:36",
    runCount: 8,
  },
  {
    id: "meeting-library",
    name: "协调纪要知识库",
    summary: "针对会议纪要、答疑记录和问题闭环说明做问答切分与摘要提取，支撑纪要内容检索。",
    status: "draft",
    docspaceIds: ["agreement-oss"],
    targetLabel: "纪要目录 / DOCX + PDF",
    preprocessStrategyIds: ["word-doc-to-docx", "pdf-to-markdown"],
    chunkingStrategyIds: ["chunk-faq", "chunk-page-window", "chunk-heading-window"],
    extractStrategyIds: ["extract-summary-points"],
    embeddingModel: "bge-m3",
    knowledgeTarget: "协调纪要知识库",
    lastRunAt: "2026-03-28 17:28",
    runCount: 4,
  },
];
