import type { PipelineRecord } from "@/knowhub/features/knowledge/types";

export const pipelineRecords: PipelineRecord[] = [
  {
    id: "survey-report-pipeline",
    name: "勘测报告",
    summary: "面向勘测资料空间中的 PDF、Word 报告，先清洗转写，再切片、提取并进入勘测知识库。",
    status: "running",
    docspaceIds: ["survey-ftp"],
    targetLabel: "勘测资料目录 / PDF + DOCX",
    preprocessStrategyIds: ["word-doc-to-docx", "pdf-to-markdown", "word-header-footer-clean"],
    chunkingStrategyIds: ["chunk-fixed-overlap", "chunk-heading-window", "chunk-table-row"],
    extractStrategyIds: ["extract-summary-points", "extract-entity-pairs"],
    embeddingModel: "bge-m3",
    knowledgeTarget: "勘测资料知识库",
    lastRunAt: "2026-03-31 10:18",
    runCount: 23,
  },
  {
    id: "standard-doc-pipeline",
    name: "标准规范入库",
    summary: "面向设计规范文档空间，对规范正文和条文做结构化切分，并统一进入标准知识库。",
    status: "published",
    docspaceIds: ["design-standards"],
    targetLabel: "全量文档 / 标准规范正文",
    preprocessStrategyIds: ["pdf-to-markdown", "word-doc-to-docx"],
    chunkingStrategyIds: ["chunk-heading", "chunk-heading-window", "chunk-standard-clause"],
    extractStrategyIds: ["extract-entity-pairs"],
    embeddingModel: "bge-large-zh-v1.5",
    knowledgeTarget: "标准规范知识库",
    lastRunAt: "2026-03-30 21:06",
    runCount: 12,
  },
  {
    id: "review-output-pipeline",
    name: "校审成果整理",
    summary: "针对校审问题台账、标准比对结果和历史闭环资料做结构切分和要点提取，形成校审经验知识库。",
    status: "draft",
    docspaceIds: ["review-ftp", "agreement-oss"],
    targetLabel: "校审成果目录 / Excel + PDF",
    preprocessStrategyIds: ["excel-table-clean", "excel-header-clean", "pdf-to-markdown"],
    chunkingStrategyIds: ["chunk-faq", "chunk-numbered-list", "chunk-page-window"],
    extractStrategyIds: ["extract-table-fields", "extract-summary-points"],
    embeddingModel: "text-embedding-3-large",
    knowledgeTarget: "校审经验知识库",
    lastRunAt: "2026-03-29 18:42",
    runCount: 6,
  },
  {
    id: "agreement-replies-pipeline",
    name: "协议回复归档",
    summary: "对协议材料 OSS 空间中的往来函件和回复成果做结构化切分与要点提取，沉淀协议回复知识库。",
    status: "published",
    docspaceIds: ["agreement-oss"],
    targetLabel: "协议回复目录 / PDF + DOCX",
    preprocessStrategyIds: ["word-doc-to-docx", "pdf-to-markdown", "word-header-footer-clean"],
    chunkingStrategyIds: ["chunk-faq", "chunk-page-window", "chunk-heading-window"],
    extractStrategyIds: ["extract-summary-points"],
    embeddingModel: "bge-m3",
    knowledgeTarget: "协议回复知识库",
    lastRunAt: "2026-03-31 08:36",
    runCount: 18,
  },
  {
    id: "table-ledger-pipeline",
    name: "清册台账入库",
    summary: "面向 Excel 清册和台账资料，先做表头清洗与表体规整，再按表格主题入库。",
    status: "published",
    docspaceIds: ["review-ftp", "survey-ftp"],
    targetLabel: "台账目录 / XLSX",
    preprocessStrategyIds: ["excel-sheet-split", "excel-header-clean", "excel-table-clean"],
    chunkingStrategyIds: ["chunk-table-row", "chunk-table-topic"],
    extractStrategyIds: ["extract-table-fields"],
    embeddingModel: "text-embedding-3-large",
    knowledgeTarget: "清册台账知识库",
    lastRunAt: "2026-03-30 16:12",
    runCount: 15,
  },
  {
    id: "meeting-minutes-pipeline",
    name: "协调纪要整理",
    summary: "针对会议纪要、答疑记录和问题闭环说明做问答切分与摘要提取，支持快速检索关键决策。",
    status: "running",
    docspaceIds: ["agreement-oss", "review-ftp"],
    targetLabel: "纪要目录 / DOCX + PDF",
    preprocessStrategyIds: ["word-doc-to-docx", "pdf-to-markdown"],
    chunkingStrategyIds: ["chunk-faq", "chunk-numbered-list", "chunk-page-window"],
    extractStrategyIds: ["extract-summary-points", "extract-entity-pairs"],
    embeddingModel: "bge-large-zh-v1.5",
    knowledgeTarget: "协调纪要知识库",
    lastRunAt: "2026-03-31 09:14",
    runCount: 9,
  },
  {
    id: "survey-photo-index-pipeline",
    name: "踏勘资料索引",
    summary: "面向踏勘记录、报告和照片说明做正文切分和实体提取，形成踏勘资料检索入口。",
    status: "draft",
    docspaceIds: ["survey-ftp"],
    targetLabel: "踏勘目录 / PDF + DOCX + ZIP 清单",
    preprocessStrategyIds: ["word-doc-to-docx", "pdf-to-markdown"],
    chunkingStrategyIds: ["chunk-fixed-overlap", "chunk-heading", "chunk-page-window"],
    extractStrategyIds: ["extract-entity-pairs"],
    embeddingModel: "bge-m3",
    knowledgeTarget: "踏勘资料知识库",
    lastRunAt: "2026-03-28 17:28",
    runCount: 4,
  },
];
