import type { ToolRecord } from "./types";

export const toolRecords: ToolRecord[] = [
  {
    id: "search-tool",
    name: "搜索工具",
    description: "检索公开网页、新闻、标准动态、厂家资料。",
    invokeType: "API",
    calls: "482",
    featured: true,
    emoji: "🔎",
    category: "网络检索",
  },
  {
    id: "site-search-tool",
    name: "指定站点搜索",
    description: "基于用户需求，搜索某个指定的网站，达成任务目标。",
    invokeType: "API",
    calls: "236",
    featured: false,
    emoji: "🌐",
    category: "网络检索",
  },
  {
    id: "web-crawler-tool",
    name: "网页爬取",
    description: "批量抓取网页正文、图片、表格、链接。",
    invokeType: "API / SDK",
    calls: "198",
    featured: false,
    emoji: "🕸️",
    category: "网络检索",
  },
  {
    id: "standard-search-tool",
    name: "法规规范检索",
    description: "面向国标、行标、地标等标准规划进行精确检索。",
    invokeType: "API",
    calls: "421",
    featured: true,
    emoji: "📚",
    category: "网络检索",
  },
  {
    id: "academic-patent-search-tool",
    name: "学术/专利检索",
    description: "找论文、专利、技术路线参考资料。",
    invokeType: "API",
    calls: "167",
    featured: false,
    emoji: "🧠",
    category: "网络检索",
  },
  {
    id: "pdf-ocr-tool",
    name: "图片PDF-OCR识别",
    description: "识别扫描件、图片、拍照件中的文字。",
    invokeType: "API",
    calls: "386",
    featured: true,
    emoji: "🧾",
    category: "文档处理",
  },
  {
    id: "pdf-structure-parse-tool",
    name: "文字PDF-结构化解析",
    description: "提取标题、正文、附表、图片说明、页码。",
    invokeType: "API",
    calls: "244",
    featured: false,
    emoji: "📄",
    category: "文档处理",
  },
  {
    id: "table-ocr-tool",
    name: "表格 OCR 工具",
    description: "把Excel表格转成MD或Json。",
    invokeType: "API / SDK",
    calls: "152",
    featured: false,
    emoji: "📋",
    category: "文档处理",
  },
  {
    id: "office-convert-tool",
    name: "Word/Excel/PPT 转换工具",
    description: "读取 Office 文档，把旧格式统一转换新格式。",
    invokeType: "API",
    calls: "215",
    featured: false,
    emoji: "🗂️",
    category: "文档处理",
  },
  {
    id: "cad-metadata-tool",
    name: "CAD/DWG 元数据解析工具",
    description: "读取图层、块、标注、文字、图签信息。",
    invokeType: "API / SDK",
    calls: "126",
    featured: false,
    emoji: "📐",
    category: "文档处理",
  },
  {
    id: "doc-diff-tool",
    name: "文档差异比对工具",
    description: "对比两个版本的报告、清单、图纸说明差异。",
    invokeType: "API",
    calls: "179",
    featured: false,
    emoji: "🆚",
    category: "文档处理",
  },
  {
    id: "coordinate-transform-tool",
    name: "坐标转换工具",
    description: "支持常见坐标系互转、投影转换。",
    invokeType: "API",
    calls: "201",
    featured: false,
    emoji: "📍",
    category: "地理空间",
  },
  {
    id: "gis-layer-reader-tool",
    name: "地图/GIS 图层读取工具",
    description: "读取 shp、geojson、kml、wms/wmts 等图层。",
    invokeType: "API / SDK",
    calls: "338",
    featured: true,
    emoji: "🗺️",
    category: "地理空间",
  },
  {
    id: "dem-profile-tool",
    name: "高程/DEM 剖面提取工具",
    description: "提取高程、坡度、纵断面信息。",
    invokeType: "API",
    calls: "149",
    featured: false,
    emoji: "⛰️",
    category: "地理空间",
  },
  {
    id: "weather-data-tool",
    name: "气象数据查询工具",
    description: "获取风速、温度、覆冰、湿度等环境数据。",
    invokeType: "API",
    calls: "227",
    featured: false,
    emoji: "🌦️",
    category: "地理空间",
  },
  {
    id: "database-query-tool",
    name: "数据库查询工具",
    description: "查询项目库、设备库、价格库、标准件库。",
    invokeType: "API / SDK",
    calls: "364",
    featured: true,
    emoji: "🗃️",
    category: "通用工具",
  },
  {
    id: "file-transfer-tool",
    name: "文件上传下载工具",
    description: "支持对象存储、共享目录、成果包拉取。",
    invokeType: "API / SDK",
    calls: "194",
    featured: false,
    emoji: "📤",
    category: "通用工具",
  },
  {
    id: "notify-tool",
    name: "邮件/短信/IM 通知工具",
    description: "把结果推送给设计人员、项目经理、校审人。",
    invokeType: "API",
    calls: "173",
    featured: false,
    emoji: "📣",
    category: "通用工具",
  },
  {
    id: "rpa-tool",
    name: "浏览器/RPA 自动化工具",
    description: "自动登录系统、填表、下载回执、抓状态。",
    invokeType: "API / SDK",
    calls: "129",
    featured: false,
    emoji: "🤖",
    category: "通用工具",
  },
  {
    id: "approval-trigger-tool",
    name: "审批触发工具",
    description: "发起流程、更新状态、回写办理结果。",
    invokeType: "API",
    calls: "156",
    featured: false,
    emoji: "🔁",
    category: "通用工具",
  },
  {
    id: "template-generator-tool",
    name: "文档模板生成工具",
    description: "按模板输出说明书、表单、清单、函件。",
    invokeType: "API",
    calls: "208",
    featured: false,
    emoji: "🧩",
    category: "内容辅助",
  },
  {
    id: "chart-flow-generator-tool",
    name: "图表与流程图生成工具",
    description: "把结果直接生成柱图、对比图、流程图、架构图。",
    invokeType: "API",
    calls: "188",
    featured: false,
    emoji: "📈",
    category: "内容辅助",
  },
  {
    id: "speech-transcribe-tool",
    name: "语音转写工具",
    description: "会议录音转文字、自动分段和摘要。",
    invokeType: "API / SDK",
    calls: "112",
    featured: false,
    emoji: "🎙️",
    category: "内容辅助",
  },
  {
    id: "file-desensitize-tool",
    name: "文件脱敏工具",
    description: "对敏感Excel、Word等文档进行数据脱敏操作。",
    invokeType: "API",
    calls: "94",
    featured: false,
    emoji: "🛡️",
    category: "内容辅助",
  },
];
