import type { DocSpaceRecord } from "@/knowhub/features/docspaces/types";

export const docSpaceRecords: DocSpaceRecord[] = [
  {
    id: "design-standards",
    name: "设计规范文档空间",
    summary: "沉淀标准规范、典设条文和常用审查依据，作为院内通用知识底座。",
    sourceType: "manual",
    status: "empty",
    documentCount: 0,
    folderCount: 0,
    totalSizeLabel: "0 MB",
    connectedTarget: "空白空间",
    owner: "标准组",
    lastSyncAt: "未同步",
    files: [],
  },
  {
    id: "survey-ftp",
    name: "勘测资料 FTP 空间",
    summary: "接入 FTP 目录中的地勘报告、路径踏勘记录和测量成果，按文件夹自动巡检。",
    sourceType: "ftp",
    status: "ready",
    documentCount: 28,
    folderCount: 6,
    totalSizeLabel: "268 MB",
    connectedTarget: "ftp://10.23.8.15/project/survey",
    owner: "勘测组",
    lastSyncAt: "2026-03-30 09:40",
    files: [
      {
        id: "ftp-1",
        name: "沿线地质勘察报告.pdf",
        path: "/2026/Q1/沿线地质勘察报告.pdf",
        sizeLabel: "18.2 MB",
        updatedAt: "2026-03-29 18:22",
        statusLabel: "已发现",
      },
      {
        id: "ftp-2",
        name: "现场踏勘记录.docx",
        path: "/2026/Q1/现场踏勘记录.docx",
        sizeLabel: "2.8 MB",
        updatedAt: "2026-03-29 17:06",
        statusLabel: "待处理",
      },
      {
        id: "ftp-3",
        name: "地形通道照片集.zip",
        path: "/2026/Q1/地形通道照片集.zip",
        sizeLabel: "126 MB",
        updatedAt: "2026-03-28 11:31",
        statusLabel: "已归档",
      },
    ],
  },
  {
    id: "agreement-oss",
    name: "协议材料 OSS 空间",
    summary: "接入 OSS 桶中的协议报批材料、来往函件和权属回复成果，保持桶内快照同步。",
    sourceType: "oss",
    status: "syncing",
    documentCount: 43,
    folderCount: 8,
    totalSizeLabel: "1.6 GB",
    connectedTarget: "oss://power-design/agreements",
    owner: "线路组",
    lastSyncAt: "2026-03-30 10:05",
    files: [
      {
        id: "oss-1",
        name: "跨越铁路回复函.pdf",
        path: "replies/跨越铁路回复函.pdf",
        sizeLabel: "5.4 MB",
        updatedAt: "2026-03-30 09:58",
        statusLabel: "同步中",
      },
      {
        id: "oss-2",
        name: "林地报批清单.xlsx",
        path: "approval/林地报批清单.xlsx",
        sizeLabel: "1.1 MB",
        updatedAt: "2026-03-29 21:12",
        statusLabel: "已发现",
      },
      {
        id: "oss-3",
        name: "村镇协调纪要.docx",
        path: "meeting/村镇协调纪要.docx",
        sizeLabel: "860 KB",
        updatedAt: "2026-03-29 15:40",
        statusLabel: "待处理",
      },
    ],
  },
  {
    id: "review-ftp",
    name: "校审成果 FTP 空间",
    summary: "沉淀通用校审意见、标准引用比对结果和历史项目问题闭环资料。",
    sourceType: "ftp",
    status: "ready",
    documentCount: 16,
    folderCount: 4,
    totalSizeLabel: "146 MB",
    connectedTarget: "ftp://10.23.8.21/review/output",
    owner: "校审组",
    lastSyncAt: "2026-03-29 20:18",
    files: [
      {
        id: "review-1",
        name: "校审问题台账.xlsx",
        path: "/review/校审问题台账.xlsx",
        sizeLabel: "3.2 MB",
        updatedAt: "2026-03-29 20:16",
        statusLabel: "已发现",
      },
      {
        id: "review-2",
        name: "标准引用比对结果.pdf",
        path: "/review/标准引用比对结果.pdf",
        sizeLabel: "7.3 MB",
        updatedAt: "2026-03-28 14:48",
        statusLabel: "已归档",
      },
    ],
  },
];
