import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
const dir=path.join(process.cwd(),"storage","appfactory"); const file=path.join(dir,"appfactory.db"); let db:Database.Database|undefined;
export function getAppFactoryDatabase(){ if(db)return db; fs.mkdirSync(dir,{recursive:true}); db=new Database(file); db.pragma("journal_mode = WAL"); db.pragma("foreign_keys = ON"); db.pragma("busy_timeout = 5000"); db.exec(`CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',skill_profile TEXT NOT NULL DEFAULT 'nextjs-build',agenthub_mode TEXT NOT NULL DEFAULT 'disabled',workspace_path TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'idle',harness TEXT NOT NULL DEFAULT 'pi',transcript_path TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id));
CREATE TABLE IF NOT EXISTS runs (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,session_id TEXT,status TEXT NOT NULL DEFAULT 'queued',input TEXT NOT NULL DEFAULT '',output TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id));
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY,project_id TEXT,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',payload_json TEXT NOT NULL DEFAULT '{}',attempts INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS builds (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',stage TEXT NOT NULL DEFAULT 'pending',log TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS releases (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,version TEXT NOT NULL,build_id TEXT NOT NULL,artifact_path TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deployments (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,release_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'stopped',url TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS capability_bindings (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,capability_id TEXT NOT NULL,version TEXT,config_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);`); return db; }
export function listProjects(){return getAppFactoryDatabase().prepare("SELECT id,name,description,skill_profile as skillProfile,agenthub_mode as agentHubMode,workspace_path as workspacePath,created_at as createdAt,updated_at as updatedAt FROM projects ORDER BY updated_at DESC").all();}
export function createProject(input:{name:string;description?:string;skillProfile?:string;agentHubMode?:string}){const id=`project-${crypto.randomUUID()}`;const now=new Date().toISOString();const workspace=path.join(dir,"workspaces",id);fs.mkdirSync(workspace,{recursive:true});fs.writeFileSync(path.join(workspace,"app.yaml"),`name: ${input.name}\nversion: 0.1.0\nruntime: nextjs\nentry: app/page.tsx\nhealthPath: /\ncapabilities: []\n`);fs.writeFileSync(path.join(workspace,"dev_todo.md"),"# 开发任务\n\n- [ ] 描述应用需求\n");fs.writeFileSync(path.join(workspace,"dev_status.md"),"# 开发状态\n\n- 状态：初始化\n");getAppFactoryDatabase().prepare("INSERT INTO projects (id,name,description,skill_profile,agenthub_mode,workspace_path,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").run(id,input.name,input.description??"",input.skillProfile??"nextjs-build",input.agentHubMode??"disabled",workspace,now,now);return getAppFactoryDatabase().prepare("SELECT id,name,description,skill_profile as skillProfile,agenthub_mode as agentHubMode,workspace_path as workspacePath,created_at as createdAt,updated_at as updatedAt FROM projects WHERE id=?").get(id);}
export function createJob(input:{projectId:string;kind:string;payload?:unknown}){const id=`job-${crypto.randomUUID()}`;const now=new Date().toISOString();getAppFactoryDatabase().prepare("INSERT INTO jobs (id,project_id,kind,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?)").run(id,input.projectId,input.kind,JSON.stringify(input.payload??{}),now,now);return getAppFactoryDatabase().prepare("SELECT * FROM jobs WHERE id=?").get(id);}
export function getProject(id:string){return getAppFactoryDatabase().prepare("SELECT id,name,description,workspace_path as workspacePath,agenthub_mode as agentHubMode FROM projects WHERE id=?").get(id) as {id:string;name:string;description:string;workspacePath:string;agentHubMode:string}|undefined;}
export function createSession(projectId:string){const id=`session-${crypto.randomUUID()}`;const now=new Date().toISOString();getAppFactoryDatabase().prepare("INSERT INTO sessions (id,project_id,status,harness,created_at,updated_at) VALUES (?,?,?,?,?,?)").run(id,projectId,"idle","pi",now,now);return getAppFactoryDatabase().prepare("SELECT id,project_id as projectId,status,harness,created_at as createdAt,updated_at as updatedAt FROM sessions WHERE id=?").get(id);}
export function listSessions(projectId:string){return getAppFactoryDatabase().prepare("SELECT id,project_id as projectId,status,harness,created_at as createdAt,updated_at as updatedAt FROM sessions WHERE project_id=? ORDER BY created_at DESC").all(projectId);}
export function setSessionStatus(id:string,status:string){getAppFactoryDatabase().prepare("UPDATE sessions SET status=?,updated_at=? WHERE id=?").run(status,new Date().toISOString(),id);}
export function claimJob(){const db=getAppFactoryDatabase();const job=db.prepare("SELECT * FROM jobs WHERE status='queued' OR (status='running' AND updated_at < datetime('now','-5 minutes')) ORDER BY created_at LIMIT 1").get() as {id:string}|undefined;if(!job)return null;db.prepare("UPDATE jobs SET status='running',attempts=attempts+1,updated_at=? WHERE id=?").run(new Date().toISOString(),job.id);return db.prepare("SELECT * FROM jobs WHERE id=?").get(job.id);}
export function finishJob(id:string,status:"completed"|"failed",error?:string){getAppFactoryDatabase().prepare("UPDATE jobs SET status=?,payload_json=CASE WHEN ? IS NULL THEN payload_json ELSE json_set(payload_json,'$.error',?) END,updated_at=? WHERE id=?").run(status,error??null,error??null,new Date().toISOString(),id);return getAppFactoryDatabase().prepare("SELECT * FROM jobs WHERE id=?").get(id);}
export function bindCapability(projectId:string,capabilityId:string,version?:string){const id=`binding-${crypto.randomUUID()}`;const now=new Date().toISOString();getAppFactoryDatabase().prepare("INSERT INTO capability_bindings (id,project_id,capability_id,version,created_at) VALUES (?,?,?,?,?)").run(id,projectId,capabilityId,version??null,now);return getAppFactoryDatabase().prepare("SELECT * FROM capability_bindings WHERE id=?").get(id);}
